#+TITLE: Managing Let's Encrypt TLS Certificates


* Preliminaries

** Install EFF's Certbot

#+begin_src sh
  sudo apt install --yes certbot
#+end_src

* certbot command idioms

** Request a new certificate

This invocation does the following:

  - =certonly=: acquire the certificate and save it to the local file
    system without changing the HTTP server's configuration
  - =--domain ...=: request a certificate for the specified FQDNs
  - =--webroot --webroot-path ...= use Certbot's "webroot"
    authentication method

#+begin_src sh
  sudo certbot certonly \
       --domain howardabrams.com \
       --domain www.howardabrams.com \
       --webroot \
       --webroot-path /var/www/html
#+end_src

In webroot authentication, certbot writes a uniquely-named file into
the HTTP server's document root directory. Let's Encrypt's server
requests this file and if successful, considers the request authentic
and issues a cert.

certbot writes the cert into its configuration directory.  See below
for the directory structure.

*** Configure the HTTP server

Assumptions:

  - 


#+begin_src sh

  # Disable sites with configuration problems
  for site in abramsdesigns affectedgeneration bednark markstruzan tiffanyabrams; do
    sudo a2dissite $site
  done

  # Enable the proxy and ssl modules
  for module in proxy ssl; do
    sudo a2enmod $module
  done
#+end_src


** Renew a certificate

A Let's Encrypt certificate is valid for 90 days, at which point one
needs to renew it.

#+begin_src sh
#+end_src


** View managed certificates

#+begin_src sh
#+end_src

* Configuration files and directories

certbot maintains its configuration in =/etc/letsencrypt=:

#+begin_src text
  /etc/letsencrypt/
    live/<domain>/                                   # <domain>'s active cert and key, symlinks to archive/<domain>/*
      cert.pem -> ../../archive/cert1.pem
      chain.pem -> ../../archive/chain1.pem
      fullchain.pem -> ../../archive/fullchain1.pem
      privkey.pem -> ../../archive/privkey1.pem
    /renewal/<domain>.conf                            # Config to use when renewing <domain>
    archive/<domain>/                                # Archive of <domain>'s old certs and keys
      chain1.pem
      privkey1.pem
      fullchain1.pem
      cert1.pem
#+end_src

=live/<domain>= contain <domain>'s active cert and key. The files
within symlink to counterparts in =archive/<domain>=.

=archive/<domain>= contain current and past generation of keys and
certificates. The files belonging to each generation end in a serial
number. A domain for which Let's Encrypt has issued four certificates
would have these files beneath =/etc/letsencrypt/archive/<domain>=:

#+begin_src text
  chain1.pem
  fullchain1.pem
  cert1.pem
  privkey1.pem
  chain2.pem
  fullchain2.pem
  cert2.pem
  privkey2.pem
  chain3.pem
  fullchain3.pem
  cert3.pem
  privkey3.pem
  chain4.pem
  fullchain4.pem
  cert4.pem
  privkey4.pem
#+end_src

* Let's Encrypt documentation

https://eff-certbot.readthedocs.io
