#+TITLE: Managing Let's Encrypt TLS Certificates


* Preliminaries

** Install EFF's Certbot

#+begin_src sh
  sudo apt install --yes certbot
#+end_src

* Configuration files and directories

certbot maintains certificates its configuration

=/etc/letsencrypt=


* certbot command idioms

** Request a new certificate

This invocation does the following:

  - =certonly=: acquire the certificate and save it to the local file
    system without changing the HTTP server's configuration
  - =--domain ...=: request a certificate for the specified FQDNs
  - =--webroot --webroot-path ...= use Certbot's "webroot"
    authentication method

#+begin_src sh
  sudo certbot certonly \
       --domain howardabrams.com \
       --domain www.howardabrams.com \
       --webroot \
       --webroot-path /var/www/html
#+end_src

In webroot authentication, certbot writes a uniquely-named file into
the HTTP server's document root directory. Let's Encrypt's server
requests this file and if successful, considers the request authentic.

certbot writes the certificate into its configuration directory.  See
below for the directory structure.

*** Configure the HTTP server

Assumptions:

  - 


#+begin_src sh

  # Disable sites with configuration problems
  for site in abramsdesigns affectedgeneration bednark markstruzan tiffanyabrams; do
    sudo a2dissite $site
  done

  # Enable the proxy and ssl modules
  for module in proxy ssl; do
    sudo a2enmod $module
  done
#+end_src


** Renew a certificate

A Let's Encrypt certificate is valid for 90 days, at which point one
needs to renew it.

#+begin_src sh
#+end_src


** View managed certificates

#+begin_src sh
#+end_src

* Let's Encrypt documentation

https://eff-certbot.readthedocs.io


